### ISSUE TITLE
Unresolved external symbol ht_up_find

### ISSUE THREAD

**Issue by Andr0pov** [rizinorg/rz-ghidra#207]
I'm trying to compile rz-ghidra with cmake on Windows 10, and getting this(I removed unnecessary output):
```
PS >rizin -v
rizin 0.2.0-git @ windows-x86-64
commit: 6b3c58ebfaeb71a72737a2e60acd952f51ea96ed, build: Sun 03/14/2021__14:40:17.82
PS >git clone https://github.com/rizinorg/rz-ghidra
PS >cd rz-ghidra
PS >git submodule init
PS >git submodule update
PS >mkdir build
PS >cd build
PS >cmake -DCMAKE_INSTALL_PREFIX=C:/PROGRA~1/Rizin/include/librz -G Ninja
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.28.29335.0
-- The CXX compiler identification is MSVC 19.28.29335.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Program Files/VisualStudio/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Program Files/VisualStudio/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Rizin: Rizin::librz
-- Configuring done
-- Generating done
-- Build files have been written to: C:/User/Downloads/rz-ghidra/build
PS >cmake --build .
Generating Code...
     Creating library C:/User/Downloads/rz-ghidra/build/Debug/core_ghidra.lib and object C:/User/Downloads/rz-ghidra/
  build/Debug/core_ghidra.exp
RizinScope.obj : error LNK2019: unresolved external symbol ht_up_find referenced in function "private: class Symbol * __cdecl RizinScope::registerFlag(struct rz_flag_item_t *)const " (?registerFlag@RizinScope@@AEBAPEAVSymbol@@PEAUrz_flag_item_t@@@Z) [C:\User\Downloads\rz-ghidra\build\core_ghidra.vcxproj]
C:\User\Downloads\rz-ghidra\build\Debug\core_ghidra.dll : fatal error LNK1120: 1 unresolved externals [C:\User\Downloads\rz-ghidra\build\core_ghidra.vcxproj]
```

**Comment by XVilka** [comment]
Introduced in https://github.com/rizinorg/rz-ghidra/commit/e79ee2a76073585c84af4fdcbbd54b24d2b3c032

**Comment by XVilka** [comment]
Should be fixed once https://github.com/rizinorg/rizin/pull/951 is merged.

**Comment by XVilka** [comment]
Fixed by https://github.com/rizinorg/rz-ghidra/commit/452d3a62ede6f7b71ea8cf73f7a1e8d47c0d3c35
